name: CI - Tests (debug)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug: show pwd and list files
        run: |
          echo "PWD: $(pwd)"
          echo "List root:"
          ls -la
          echo "List .github:"
          ls -la .github || true
          echo "List .github/workflows:"
          ls -la .github/workflows || true
          echo "Show requirements.txt if present:"
          if [ -f requirements.txt ]; then
            echo "requirements.txt exists, contents:"
            sed -n '1,200p' requirements.txt
          else
            echo "requirements.txt NOT FOUND"
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest -q
